-- require("config.ui2")
require("config.lsp-keymaps")
require("config.lazy")
require("config.treesitter-highlight")
require("config.focus-dim")
require("config.eqalize-split")
require("config.options")
require("config.zenhan")
require("config.treemux-sync")
require("config.diagnostics")
