format = """
${custom.wsl}\
[ ](fg:color_aqua bg:color_yellow)\
$username\
[ ](fg:color_yellow bg:color_blue)\
$directory\
[ ](fg:color_blue bg:color_orange)\
$git_branch\
$git_status\
[ ](fg:color_orange bg:color_gray)\
$time\
[ ](fg:color_gray)\
$cmd_duration\
\n$character
"""
palette = "theme"

# set color theme
[palettes.theme]
color_white = "#fbf1c7"
color_blue = "#0080ff"
color_aqua = "#008fad"
color_yellow = "#b49125"
color_orange = "#d65d0e"
color_gray = "#3d3836"

# add one space between command line 
add_newline = "true"

[custom.wsl]
command = "echo $WSL_DISTRO_NAME"
when = "test -n \"$WSL_DISTRO_NAME\""
format = "[ 󰍺  $output ]($style)" 
style = "fg:color_white bg:color_aqua"
disabled = false

[username]
show_always = true
style_user = "fg:color_white bg:color_yellow"
style_root = "fg:color_white bg:color_yellow"
format = "[ $user ]($style)"
disabled = false

[directory]
style = "fg:color_white bg:color_blue"
truncation_length = 10
truncate_to_repo = false
truncation_symbol = "…/"
read_only = ' 󰌾 '
read_only_style = 'fg:color_yellow bg:color_blue'
format = '[  $path ]($style)[$read_only]($read_only_style)'

[aws]
disabled = true
[gcloud]
disabled = true

[git_branch]
symbol = ""
style = "fg:color_white bg:color_orange"
format = '[[$symbol $branch ](fg:color_white bg:color_orange)]($style)'

[git_status]
style = "bg:#1d2230"
format = '[[($all_status$ahead_behind )](fg:color_white bg:color_orange)]($style)'

[cmd_duration]
min_time = 1
style = 'fg:color_white'
format = "[✨ $duration]($style)" # nf-pl-right_soft_divider, nf-mdi-clock

[time]
disabled = false
time_format = "%r" # Hour:Minute Format
style = "bg:color_gray"
format = '[ $time ]($style)'

[character]
vimcmd_symbol = '[V](bold green) '

