gui:
  border: double
  theme:
    defaultFgColor:
      - "#d4d4d4"
    activeBorderColor:
      - "#007fff"
      - bold
    inactiveBorderColor:
      - "#666666"
    searchingActiveBorderColor:
      - "#007fff"
      - "bold"
    inactiveViewSelectedLineBgColor:
      - "#1e3a5f"
    selectedLineBgColor:
      - "#264f78"

