[application]
DefaultPageSize = 300
TreeWidth = 40
[theme]
Preset = "default"
[theme.Colors]
Border = "#007fff"
Title = "#d4d4d4"
PrimaryText = "#d4d4d4"
SecondaryText = "#add6ff"
EditorSelection = "#add6ff"
ContrastSecondaryText = "black"
[keymap.Editor]
OpenInExternalEditor = "Ctrl-E"
