-- =====================================================================================================
-- TITLE: dtrh95/csharp-explorer.nvim
-- ABOUT: Lightweight formatter plugin for Neovim
-- LINKS: https://github.com/stevearc/conform.nvim
-- =====================================================================================================
