return {
  { import = "plugins.ui.dashboard" },
  { import = "plugins.ui.vscode" },
  { import = "plugins.editor.autopairs" },
  { import = "plugins.editor.dropbar" },
  { import = "plugins.editor.indent-blankline" },
  { import = "plugins.editor.lualine" },
  { import = "plugins.editor.nerdicons" },
  { import = "plugins.editor.nvim-tree" },
  { import = "plugins.editor.nvim-treesitter" },
  { import = "plugins.editor.nvim-treesitter-context" },
  { import = "plugins.editor.oil" },
  { import = "plugins.editor.telescope" },
  { import = "plugins.lsp.blink" },
  { import = "plugins.lsp.lazydev" },
  { import = "plugins.lsp.mason" },
  { import = "plugins.lsp.mason-lspconfig" },
  { import = "plugins.lsp.mason-tool-installer" },
  { import = "plugins.lsp.nvim-lspconfig" },
}
