return {
  { import = "plugins.vim-tmux-navigator" },
  { import = "plugins.vscode-theme" },
  { import = "plugins.oil" },
  { import = "plugins.lazydev" },
  { import = "plugins.neoscroll" },
  { import = "plugins.blink-cmp" },
  { import = "plugins.blink-pairs" },
  { import = "plugins.blink-indent" },
  { import = "plugins.nvim-surround" },
  { import = "plugins.conform" },
  { import = "plugins.telescope" },
  { import = "plugins.mason-lspconfig" },
  { import = "plugins.mason-tool-installer" },
  { import = "plugins.nvim-treesitter" },
  { import = "plugins.treesj" },
  { import = "plugins.vim-doge" },
  { import = "plugins.dropbar" },
  { import = "plugins.lualine" },
  { import = "plugins.nvim-notify" },
  { import = "plugins.noice" },
  { import = "plugins.which-key" },
  { import = "plugins.typescript-tools" },
  { import = "plugins.roslyn" },
  { import = "plugins.nvim-lint" },
  { import = "plugins.rest-nvim" },
  { import = "plugins.virt-column" },
}
