set -g @bg  "#121212"
set -g @bg-inactive "#2d2d2d"
set -g @fg  "#d4d4d4"
set -g @black "#121212"
set -g @white "#d4d4d4"
set -g @red "#f5511e"
set -g @blue "#569cd6"
set -g @green "#6a9955"
set -g @cyan "#56b6c2"
set -g @purple "#c586c0"
set -g @yellow "#dcdcaa"
set -g @brightBlack "#5f6672"
set -g @brightWhite "#d4d7d9"
set -g @brightRed "#f44747"
set -g @brightBlue "#007fff"
set -g @brightGreen "#66ff00"
set -g @brightCyan "#08e8de"
set -g @brightPurple "#8b00ff"
set -g @brightYellow "#ffd600"
