# import source files
source-file ~/.config/dotfiles/tmux/colors.conf

# prefix: C-t
unbind C-b
set -g prefix C-t
bind C-t send-prefix

# unbind Space (for Neovim)
unbind Space

# set vim-keybind
setw -g mode-keys vi

# enable mouse
set -g mouse on

# enable clipboard
set -g set-clipboard on
set -g allow-passthrough on

# enable focus-events
set -g focus-events on

# enable 24-bit true color in tmux
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# time
set -gs escape-time 10

# index from 1
set -g base-index 1
setw -g pane-base-index 1

# set renumber-windows when close other window
set -g renumber-windows on

# status-bar
set -g status-position top
set -g status-style "bg=#{@bg},fg=#{@fg}"
set -g status-left "#{?client_prefix,#[bg=#{@brightYellow} fg=#{@bg}] PREFIX ,#[bg=default] #S }"
set -g status-left-length 20
set -g status-right "%Y/%m/%d %H:%M"
set -g status-interval 5

setw -g window-status-format " #I:#W "
setw -g window-status-current-format " #[fg=#{@fg},bg=#{@brightBlue},bold]  #I:#W  "
setw -g window-status-style "fg=#{@fg},bg=#{@bg}"

# appearance of pane status
set -g pane-border-status top
set -g pane-border-format "#{pane_title}"

# background color of active or inactive pane
# NOTE: this setting doesn't work in Neovim
set -g window-style "bg=#{@bg-inactive}"
set -g window-active-style "bg=#{@bg}"

# border color of active or inactive pane
set -g pane-border-style "fg=#{@fg}"
set -g pane-active-border-style \
  "#{?pane_in_mode,fg=#{@brightYellow},#{?synchronize-panes,fg=#{@red},#{?window_zoomed_flag,fg=#{@brightGreen},fg=#{@brightBlue}}}}"

# set the default pane name to empty
set -g allow-set-title off
set-hook -g after-new-session 'select-pane -T " terminal "'
set-hook -g after-new-window 'select-pane -T " terminal "'
set-hook -g after-split-window 'select-pane -T ""'

# pane navigation
bind -N "Move to left pane" -n C-h if-shell -F '#{window_zoomed_flag}' '' 'select-pane -L'
bind -N "Move to below pane" -n C-j if-shell -F '#{window_zoomed_flag}' '' 'select-pane -D'
bind -N "Move to above pane" -n C-k if-shell -F '#{window_zoomed_flag}' '' 'select-pane -U'
bind -N "Move to right pane" -n C-l if-shell -F '#{window_zoomed_flag}' '' 'select-pane -R'
bind -N "Move to left pane" -T copy-mode-vi C-h if-shell -F '#{window_zoomed_flag}' '' 'select-pane -L'
bind -N "Move to below pane" -T copy-mode-vi C-j if-shell -F '#{window_zoomed_flag}' '' 'select-pane -D'
bind -N "Move to above pane" -T copy-mode-vi C-k if-shell -F '#{window_zoomed_flag}' '' 'select-pane -U'
bind -N "Move to right pane" -T copy-mode-vi C-l if-shell -F '#{window_zoomed_flag}' '' 'select-pane -R'

# rename pane-name
bind -N "Rename current pane" + command-prompt -I "#{pane_title}" "select-pane -T ' %% '"

# split-pane 
bind -N "Split window vertically" V split-window -h -c "#{pane_current_path}"
bind -N "Split window horizontally" H split-window -v -c "#{pane_current_path}"

# resize pane
bind -N "Resize the pane left" -r h resize-pane -L 5
bind -N "Resize the pane down" -r j resize-pane -D 5
bind -N "Resize the pane up" -r k resize-pane -U 5
bind -N "Resize the pane right" -r l resize-pane -R 5

# set IME-off when move pane and window
set-hook -g pane-focus-in 'run-shell -b "~/.config/dotfiles/scripts/zenhan-off.sh"'

# copy mode
bind -N "begin selection (copy mode)" -T copy-mode-vi v send -X begin-selection
bind -N "select line (copy mode)" -T copy-mode-vi V send -X select-line
bind -N "copy and exit copy mode" -T copy-mode-vi y send -X copy-pipe-and-cancel "clip.exe"

# lazydocker
bind -N "Open lazydocker" D new-window -n lazydocker -c "#{pane_current_path}" "lazydocker; kill-window"

# lazygit
bind -N "Open lazygit" G new-window -n lazygit -c "#{pane_current_path}" "lazygit; kill-window"

# reload .tmux.conf
bind -N "Reload tmux.conf" r source-file ~/.config/dotfiles/tmux/tmux.conf \; display-message "Reloaded tmux.conf"

